#!/usr/bin/env python3
# encoding: utf-8

'''
@author: Milos Subotic <milos.subotic.sm@gmail.com>
@license: MIT
'''

###############################################################################

from common_waf import *
import avrwaf
import avrwaf.arduino

import os

###############################################################################

def prerequisites(ctx):
	ctx.load('arduino', tooldir = avrwaf.location)

def options(opt):
	opt.load('c cxx')
	# Common options.
	opt.add_option(
		'--app',
		dest = 'app',
		default = None,
		help = 'App to be uploaded to MCU'
	)
	opt.add_option(
		'--port',
		dest = 'port',
		default = None,
		help = 'Programmer port number or full file name i.e. dev file ' +
			'(2, /dev/ttyUSB2, COM2)'
	)

	# Project specific.
	opt.add_option(
		'--wavgat',
		dest = 'wavgat',
		action = 'store_true',
		default = False,
		help = 'WAVGAT version of Arduino'
	)

def configure(cfg):
	if cfg.options.wavgat:
		cfg.env.ARDUINO_BOARD = 'WAVGAT UNO R3'
	else:
		cfg.env.ARDUINO_BOARD = 'Arduino Uno'
	if cfg.options.port:
		cfg.env.PROGRAMMER_PORT = expand_port(cfg.options.port)

	cfg.env.OPT = '-Os'
	# Tools.
	cfg.load('arduino', tooldir = avrwaf.location)
	cfg.load('avr', tooldir = avrwaf.location)
	cfg.load('avrdude', tooldir = avrwaf.location)

	s3a_serial_main = cfg.srcnode.find_node(
		'../../ROS/s5a_ws/src/s5a_serial_main/'
	)
	cfg.check(
		uselib_store = 'from_s3a_serial_main',
		msg = "Checking for stuff from 's3a_serial_main'",
		header_name = 'motor_ctrl_pkgs.hpp',
		includes = str(s3a_serial_main.find_node('include')),
		features = 'cxx cxxprogram',
		mandatory = True
	)


def build(bld):
	# Build Arduino_Core.
	avrwaf.arduino.build(bld)

	bld.stlib(
		target = 'VarSpeedServo',
		source = ['VarSpeedServo.cpp'],
		use = 'Arduino_Core',
		includes = '.',
		export_includes = '.'
	)

	for code_file in glob_apps_srcs(bld):
		name = os.path.splitext(code_file)[0]
		bld.program(
			target = name + '.elf',
			features = 'avr-hex',
			use = 'Arduino_Core from_s3a_serial_main VarSpeedServo',
			source = [code_file]
		)
		#TODO Move to feature.
		bld(
			rule = '"${OBJDUMP}" -S "${SRC}" > "${TGT[0]}"',
			target = name + '.asm',
			source = name + '.elf'
		)


###############################################################################

@after_cmd(build)
@build_context
def size(ctx):
	'''Size of firmware choosed by --app=<NAME> or all'''
	if ctx.options.app:
		a = expand_app(ctx.options.app)
		ctx(
			features = 'avr_size',
			source = 'build/' + a + '.elf'
		)

@build_context
def reset(ctx):
	'''Reset MCU'''
	ctx(features = 'avrdude_read_fuses')

@build_context
def read_fuses(ctx):
	'''Read fuses from MCU'''
	ctx(features = 'avrdude_read_fuses')

@build_context
def write_fuses(ctx):
	'''Write configured fuses from MCU'''
	ctx(features = 'avrdude_write_fuses')


def common_upload(ctx, verify_only):
	if ctx.options.port:
		ctx.env.PROGRAMMER_PORT = expand_port(ctx.options.port)
	if ctx.options.app:
		a = expand_app(ctx.options.app)
		ctx(
			features = 'avrdude_upload',
			source = a + '.hex',
			verify_only = verify_only
		)
@after_cmd(build)
@build_context
def upload(ctx):
	'''Upload firmware <NAME>.hex to MCU choosed by --app=<NAME>'''
	common_upload(ctx, False)
@after_cmd(build)
@build_context
def verify(ctx):
	common_upload(ctx, True)

###############################################################################
