controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint0_shoulder_pan
      - joint1_shoulder_lift
      - joint2_elbow
      - joint3_wrist_flap
      - joint4_wrist_rot
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - joint4_wrist_rot
initial:  # Define initial robot poses per group
#  - group: arm
#    pose: home

  []